### PR TITLE
feat: use pipe-delimited collections

### PR DESCRIPTION
**Pull request by egdbear**
Gravity PR - https://github.com/artsy/gravity/pull/16029
[Ticket](https://artsyproduct.atlassian.net/browse/DO-421)

### CODE REVIEW

**Review by joeyAghion — COMMENTED** [review]
I'm not so familiar with this. Is it a fix, or a change?

**Comment by joeyAghion** [comment]
Got it. If there's a corresponding Zenith change, link me? Feel free to proceed with this in any case.

**Review by jonallured — APPROVED** [review]
LGTM!! 🎉

**Comment by egdbear** [comment]
> Got it. If there's a corresponding Zenith change, link me? Feel free to proceed with this in any case.

Well actually we are overwriting the data in Gravity with the new source which has been already coming from Zenith.

**Pull request merged**
