### PR TITLE
initials from/to in messages

### PR DESCRIPTION
**Pull request by l2succes**

### CODE REVIEW

**Comment by orta** [comment]
This seems weird, the Dangerfile specifically checks for an assignee - danger should have failed this

**Comment by orta** [comment]
Ah, Circle. 

screen shot 2017-07-05 at 16 10 25

Maybe I'll migrate this to Peril.

**Comment by l2succes** [comment]
@orta Yeah that's weird since it is a PR. I can try rerunning CI to see if it runs this time.

**Comment by orta** [comment]
It's this: http://danger.systems/guides/troubleshooting.html#circle-ci-doesnt-run-my-build-consistently

A re-run would fix it for this build, but Peril would fix it for all builds

**Pull request merged**
