### PR TITLE
feat: push schema updates to energy

### PR DESCRIPTION
**Pull request by MounirDhahri**
This PR makes sure that we update the schema inside energy to match the one in metaphysics to avoid manual updates like this one https://github.com/artsy/energy/pull/143

cc @rajsam003

### CODE REVIEW

**Comment by MounirDhahri** [comment]
I will merge this since it's the only way to test it out. This makes no schema changes, so we should be safe

**Comment by brainbicycle** [comment]
Woot! thanks Mounir!

**Comment by patrinoua** [comment]
@MounirDhahri I'd love some more context on this if you have time 🙏

**Comment by MounirDhahri** [comment]
sure, I will reach out

**Pull request merged**
