### PR TITLE
@ds300 => [V2 Sales] Use  a loader that resolves headers for the connection

### PR DESCRIPTION
**Pull request by mzikherman**
The loader used here should resolve headers, so added a new one since we're using batching for sales currently (which doesn't support resolving headers).

### CODE REVIEW

**Comment by ds300** [comment]
I'm still confused why the existing loader is resolving headers for me, sarah, and kieran, but not for you 🤔 

And is it OK that we're losing the batching capability of the existing loader here?

**Comment by mzikherman** [comment]
Yea, batching is mostly used for individual sales, so instead of many individual sale queries:

```
sale/id1
sale/id2
sale/id3
...
```

you'd get: `/sales?ids[]=1&ids[]=2&ids[]=3...`

So for the list/multiple loader, its not really being batched.

**Comment by alloy** [comment]
Well, that’s weird, it def did work for me too :?

**Comment by mzikherman** [comment]
I...don't see how? It seems pretty clear that the loader for multiple sales does not resolve headers, and the several specs that wind up stubbing `salesLoader` (just searching for that string in tests), all stub the underlying response (an array of sales), w/o headers.

**Comment by alloy** [comment]
There’s the `{ headers: true }` option being passed to the loader.

**Comment by mzikherman** [comment]
Oh interesting, I hadn't noticed that!

In that case it could be a usage of `salesLoader` (with the same params), but without `{ headers: true }` that caches the list w/o the headers. That might explain it.

In that case, I think this PR is correct, since due to the caching you need a wholly separate loader if the signature of the response is going to be different, based on that option. But the extraneous `{ headers: true }` [here](https://github.com/artsy/metaphysics/blob/02aecb4a780a5878fd1530d25b865611f140a25e/src/schema/v2/sales.ts#L68) can be removed.

**Comment by alloy** [comment]
Aha, I see, I see. Perhaps the cache key should take that option into account then so we can use it rather than having to define multiple loaders?

**Comment by mzikherman** [comment]
That's not a bad idea. Athough, we did clear the cache on staging and it didn't seem to resolve the issue, so there might still be some sort of bug here (maybe passing in `{headers: true}` in the resolver isn't making it through. Looking in the codebase and that's the only place we try to pass that in at resolve-time, all the others are set in the loader definitions themselves.

But then, this _worked_ for several other people, with latest `master`? Something still doesn't fully add up (although with this fix things are more explicit now).

**Pull request merged**
