### PR TITLE
Fixes the order for the artist rail

### PR DESCRIPTION
**Pull request by l2succes**
Fixes https://github.com/artsy/collector-experience/issues/177
https://github.com/artsy/emission/issues/472

### CODE REVIEW

**Comment by alloy** [comment]
Does this also change the order on Force and is that ok?

**Comment by l2succes** [comment]
@alloy I'm not sure if it changes the order in force as well but I'll find out

**Comment by l2succes** [comment]
screen shot 2017-05-11 at 4 27 49 pm

@alloy Seems like it's already in the correct order

**Comment by alloy** [comment]
Ace, thanks for checking! 👍

**Pull request merged**
