### PR TITLE
@mzikherman - use find instead of first to get artwork default image

### PR DESCRIPTION
**Pull request by broskoski**

### CODE REVIEW

**Comment by mzikherman** [comment]
Nice, JS Cop feasting on you tho :cop:

**Comment by dzucconi** [comment]
https://github.com/artsy/metaphysics/commit/72509645ac6a0254eabe7bdf14487aaa67f67b69#diff-5f34785bd3364df78197dc907162ec0aL185

**Comment by dzucconi** [comment]
I don't know why @craigspaeth changed this; I assumed that lodash had updated `first` but this appears to not be the case.

**Comment by dzucconi** [comment]
And indeed, this is the correct fix. `findWhere` became `find`

**Comment by dzucconi** [comment]
Thx for the spec

**Pull request merged**
