### PR TITLE
[Tests] Removes the global functions for schema and runQuery

### PR DESCRIPTION
**Pull request by orta**
I was on a long bus, so I took a look at TypeScript support- first by running some regexes and setting it up. Looks pretty feasible. What isn't trivial is getting the tests to work - because they all use babel-rewire, for which there's no TS equivalent. 

So this _starts_ the movement towards removing babel-rewire, by first removing some of the globals inside our tests.

### CODE REVIEW

**Comment by alloy** [comment]
Makes sense. It should be straightforward, I think, to replace the rewiring with jest mocking fwiw.

**Comment by mzikherman** [comment]
Looks straightforward to me, just replacing those global query runners with an explicit import from utils, 👍 

Some lint-ish issues tho, ❌

**Comment by orta** [comment]
cool, got it passing linters. 

Realised I didn't explain _why_ this needed to happen. This blocked using jest's mocks because the module would already have been resolved by adding it in the pre-test file setup file. So any attempts at mocking would fail because even with [Jest's mock hoisting](https://github.com/facebook/jest/issues/796) it would be too late to make the call.

**Comment by mzikherman** [comment]
Thanks for the explanation. I didn't fully get the reason but it seemed like a worthy enough change even in its own right (reducing globals), but thank you for the further clarification!

**Pull request merged**
