### PR TITLE
chore(2fa): second factor mutations require a password

### PR DESCRIPTION
**Pull request by ovasdi**
https://artsyproduct.atlassian.net/browse/PLATFORM-4340

Update gravity schema follow changes introduced in https://github.com/artsy/gravity/pull/15527

Additionally, following [this slack thread](https://artsy.slack.com/archives/CP9P4KR35/p1658341062151829), schema test is tweaked to no longer require a snapshot.

### CODE REVIEW

**Comment by mc-jones** [comment]
Sorry for my ignorance here, but I'm a bit confused by this PR. These schema files are generally auto-generated, no? Did we manually update these?

**Comment by ovasdi** [comment]
> Sorry for my ignorance here, but I'm a bit confused by this PR. These schema files are generally auto-generated, no? Did we manually update these?

@mc-jones thanks for taking a look. I haven't made a change like this before so I may be following the wrong directions. I was using [this doc](https://github.com/artsy/gravity/blob/main/doc/Graphql.md) as a reference and specifically following this step when opening this PR:

>Copy the schema file to your local Metaphysics under src/data and make a PR to Metaphysics with this change.

Is this instruction out of date perhaps?

**Comment by ovasdi** [comment]
@mc-jones Looking at [this (recent) PR](https://github.com/artsy/metaphysics/pull/4241) as an example. Seems it was also manually updated.

**Review by mzikherman — APPROVED** [review]

**Comment by mzikherman** [comment]
I think this is fine although the Danger comment seems confusing as those types aren't modified in the diff of this PR?

But yea it's correct for someone to manually update an upstream schema (such as gravity) here when needed. The `_schema` file gets updated in a pre-commit hook.

**Comment by ovasdi** [comment]
> I think this is fine although the Danger comment seems confusing as those types aren't modified in the diff of this PR?

Yea that as a bit confusing to me as well. I think the branch was a bit stale. Merged main and now its only warning about fields changed in this PR.

**Pull request merged**
