### PR TITLE
Remove the cents from the generic genes inside the home feed

### PR DESCRIPTION
**Pull request by orta**
When you compare to a response given from the refined artworks:

screen shot 2016-12-05 at 13 44 12

They only send as dollars, so the parsing code in eigen has to remove the dots and do some extra work that's not needed in comparison to how it's handled with the rest of the refine allocation data

### CODE REVIEW

**Comment by orta** [comment]
@xtina-starr can you confirm if this would break force's home feed? If I recall you ignore the price_range in the homefeed

**Comment by xtina-starr** [comment]
@orta I imagine this is fine because the query I'm seeing for genes is here https://github.com/artsy/force/blob/master/apps/home/components/gene_context/query.coffee

@broskoski would know for sure.

**Comment by broskoski** [comment]
Yep, looks fine to me!

Just fyi @xtina-starr in the future you can check by pulling down this PR,  running metaphysics locally and pointing force to the local metaphysics.

And @orta , this PR wouldn't break the homepage, it just might have sent unsupported params to gravity. I've confirmed that these values get converted by gravity to floats anyway ( https://github.com/artsy/gravity/blob/4abdf3df601844d1d3f6e2c06d908a23b0149fb0/app/api/util/filter_helpers.rb#L118 ), so we might have had them set like that due to an earlier version that expected floats.

Looks like you'll have to merge in master though, feel free to merge when thats resolved.

**Comment by xtina-starr** [comment]
@broskoski thanks for the tip!

**Comment by alloy** [comment]
Seeing as @broskoski is out tomorrow, I’ll take this one instead.

**Pull request merged**
