### PR TITLE
@mzikherman - If the partner is an auction, give the proper href

### PR DESCRIPTION
**Pull request by broskoski**
Closes https://github.com/artsy/force/issues/270

### CODE REVIEW

**Comment by broskoski** [comment]
cc @acjay

**Comment by mzikherman** [comment]
u got ❌ 'ed!

**Comment by broskoski** [comment]
I sure did, @mzikherman. I sure did.

**Comment by broskoski** [comment]
For reference, this is where it's happening: https://github.com/artsy/force/blob/master/components/artwork_metadata_stub/templates/didactics.jade#L22

**Pull request merged**
