### PR TITLE
Add totalCents and subtotalCents

### PR DESCRIPTION
**Pull request by ashkan18**
# Change
`totalCents` and `subtotalCents` were added as part of https://github.com/artsy/exchange/pull/56, this PR basically adds those to MP.

### CODE REVIEW

**Comment by jonallured** [comment]
With artsy/exchange#56 merged, I think this can land after a rebase to clear up the merge conflict. ❤️

**Comment by ashkan18** [comment]
thanks @jonallured , this is not really merge conflict, it's just saying this branch is behind `master`. It safe to merge but i can try rebase too.

**Comment by ashkan18** [comment]
just used shiny fancy "Update branch" button :)

**Comment by jonallured** [comment]
Oh nice! Let's just merge on green then! 💪

**Comment by jonallured** [comment]
@orta I was expecting this to be merged by Peril with that comment about merging on green, did I do something incorrectly?

**Pull request merged**
