### PR TITLE
docs: add docs for creating a new home view section

### PR DESCRIPTION
**Pull request by MounirDhahri**
This PR is still in progress - reviews are welcome though 👋 

This PR defines some guidelines on how to add a new home view section.

What's missing:
- [ ] Some polishing to content (better english, better links)
- [ ] Link example PR
- [ ] Add KS video link

### CODE REVIEW

**Comment by anandaroop** [comment]
@MounirDhahri I took the liberty of pushing up a big update, and incorporating links to the KS and example branches.

I feel like this doc is fairly up-to-date for now. We might certainly need to keep updating it, but maybe we can review and merge the current version?

**Comment by anandaroop** [comment]
Here's what it looks like now if any @artsy/onyx-devs have feedback: [adding_a_new_home_view_section.md](https://github.com/artsy/metaphysics/blob/24d189632c839d58891d4da8e07007217aeee516/docs/adding_a_new_home_view_section.md)

**Review by olerichter00 — APPROVED** [review]
Thanks! This is very helpful 🙇

**Comment by MounirDhahri** [comment]
Merging this to make it easier to find - also this will allow you to make changes in your PR @anandaroop

**Pull request merged**
