### PR TITLE
Add the version id to a couple places

### PR DESCRIPTION
**Pull request by jonallured**
This was missing and was causing the resolver to get an undefined.

### CODE REVIEW

**Comment by ashkan18** [comment]
nice! Just to be super safe, lets make sure Gravity PR gets deployed before merging this. what do you think?

**Comment by jonallured** [comment]
@ashkan18 yeah I don't feel strongly one way or the other so better to be safe! 🤗 

So the failure on CI seems to be about the ecommerce orders response - maybe there's another place in the fixture data where I need to add this?

**Comment by ashkan18** [comment]
I think we may need to update https://github.com/artsy/metaphysics/blob/master/src/test/fixtures/exchange/orders.json#L65 and possibly https://github.com/artsy/metaphysics/blob/master/src/test/fixtures/results/sample_order.js#L78

**Comment by jonallured** [comment]
@ashkan18 ok the Gravity change is deploying to production right now and the tests are green on this one so I think it's good to merge, what do you think?

**Comment by ashkan18** [comment]
lets do this! 🙌

**Pull request merged**
