### PR TITLE
@orta - add artworks connection to gene schema

### PR DESCRIPTION
**Pull request by broskoski**
Does some work to get artworks connection into the `Gene` schema (in order to fix your Gene page in Emission!).

screen shot 2017-02-21 at 3 28 19 pm

### CODE REVIEW

**Comment by orta** [comment]
Cool, this looks good - maybe port the artist relay tests over to the gene too?

**Comment by orta** [comment]
All looks good to me though, glad to see this moving to relay 👯

**Comment by broskoski** [comment]
Good call, just a sec, shall move!

**Comment by broskoski** [comment]
💚

**Comment by broskoski** [comment]
Mergin!

**Pull request merged**
