### PR TITLE
Update access token retrieval instructions

### PR DESCRIPTION
**Pull request by ds300**
The instructions for getting a local GraphiQL app setup were tripping me up and @alloy suggested I do this process instead, and that we should update the README to match.

### CODE REVIEW

**Comment by alloy** [comment]
Sweet ✨ 

Merge on green.

**Comment by orta** [comment]
We should also consider switching to GraphQL-playground too, that lets you set those vars in the site - then you don't need the app at all. I use it with peril: https://staging-api.peril.systems/api/graphiql?query=%7B%0A%20%20me%0A%7D

screen shot 2018-08-14 at 12 14 40 pm

**Comment by alloy** [comment]
@orta is it extensible? I’d love to surface persisted queries.

**Comment by orta** [comment]
We can pass in a set of `Tabs` - which could include all persisted queries: https://github.com/prismagraphql/graphql-playground#properties

Maybe we could also make it so that tabs aren't reset each time too

**Pull request merged**
