### PR TITLE
logged-out modules should respect requested order

### PR DESCRIPTION
**Pull request by bhoggard**
related issue: https://github.com/artsy/collector-experience/issues/362

### CODE REVIEW

**Comment by alloy** [comment]
Nice 👏

**Comment by bhoggard** [comment]
I verified this locally, but I'm not seeing it take effect on https://staging.artsy.net/. Caching in metaphysics?

**Comment by alloy** [comment]
Hmm, not that I know of. Still no dice?

**Comment by bhoggard** [comment]
This didn't show the popular works at the top. I have to figure out how that gets decided on, since the list here https://github.com/bhoggard/force/blob/master/desktop/apps/home/queries/initial.coffee#L6-L16 doesn't mention popular works.

**Pull request merged**
