### PR TITLE
Update artwork mediums

### PR DESCRIPTION
**Pull request by dblandin**
While this field is still new use and unused in production, this PR makes a few changes to the schema:

- Rename `Query#artworkMediumTypes` to `Query#artworkMediums`
- Rename internal `MediumType` type to `ArtworkMedium`
- Remove ID fields from `ArtworkMedium/MediumType` type.

The name of the artwork field is still `mediumType`.

Rebase and merge please.

cc/ @dzucconi - This will introduce some required changes to your work in Force.

### CODE REVIEW

**Review by mzikherman — APPROVED** [review]
🔥

**Comment by dzucconi** [comment]
We need to expose an `artworkMedium(type: MEDIUM)` field for querying individual mediums, as well.

**Comment by dblandin** [comment]
> We need to expose an artworkMedium(type: MEDIUM) (or whatever) field for querying individual mediums, as well.

@dzucconi Ahh, I thought that UI might be handled by `Artwork#mediumType` but maybe not?

**Comment by dblandin** [comment]
Going to go ahead and merge this in. Let's follow-up on the `artworkMedium(type: MEDIUM)` addition if needed.

**Comment by dzucconi** [comment]
@dblandin ah no you're right that's fine. I didn't know it was there. Thanks

**Pull request merged**
