### PR TITLE
@alloy: Allow "preliminary auction" for "buy now" works

### PR DESCRIPTION
**Pull request by craigspaeth**
Alessandra surfaced an issue she discovered in a staging auction where we weren't rendering the Buy now state. This was because for something to be buy nowable in MP it had to be of a certain [sale type](https://github.com/artsy/gravity/blob/master/app/models/domain/sale.rb#L46). We simply needed to account for the fact that `preliminary auction` is a valid sale type too.

Related Slack thread: https://artsy.slack.com/archives/auctions-dev/p1477314507006194

### CODE REVIEW

**Comment by orta** [comment]
Fail is legit, will get Danger on this repo soon

**Comment by alloy** [comment]
I bet it's failing because the test data for the artwork is not passing the Artwork's isTypeOf validation.

Otherwise LGTM 👍

**Comment by alloy** [comment]
@craigspaeth bump

**Comment by craigspaeth** [comment]
I think this PR https://github.com/artsy/metaphysics/pull/464 made this irrelevant. Closing, thanks @mzikherman !

**Pull request closed without merging**
