### PR TITLE
[WIP] Update graphql-tools to unblock looking at schema stitching again

### LINKED ISSUE #836: [Stitching] Issues with enums
[From Slack](https://artsy.slack.com/archives/C1HH3KNJG/p1511450516000140)

So, take [this query](https://metaphysics-staging.artsy.net/?method=post&query=query%20%7B%0A%20%20home_page%20%7B%0A%20%20%20%20artwork_modules%28%0A%20%20%20%20%20%20max_rails%3A%206%2C%0A%20%20%20%20%20%20order%3A%20%5B%0A%20%20%20%20%20%20%20%20ACTIVE_BIDS%2C%0A%20%20%20%20%20%20%20%20RECOMMENDED_WORKS%2C%0A%20%20%20%20%20%20%20%20FOLLOWED_ARTISTS%2C%0A%20%20%20%20%20%20%20%20RELATED_ARTISTS%2C%0A%20%20%20%20%20%20%20%20FOLLOWED_GALLERIES%2C%0A%20%20%20%20%20%20%20%20SAVED_WORKS%2C%0A%20%20%20%20%20%20%20%20LIVE_AUCTIONS%2C%0A%20%20%20%20%20%20%20%20CURRENT_FAIRS%2C%0A%20%20%20%20%20%20%20%20FOLLOWED_GENES%2C%0A%20%20%20%20%20%20%20%20GENERIC_GENES%5D%29%20%7B%0A%20%20%20%20%20%20key%0A%20%20%20%20%20%20params%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20related_artist_id%0A%20%20%20%20%20%20%20%20followed_artist_id%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20hero_units%28platform%3A%20DESKTOP%29%20%7B%0A%20%20%20%20%20%20mode%0A%20%20%20%20%20%20heading%0A%20%20%20%20%20%20title%0A%20%20%20%20%20%20title_image_url%0A%20%20%20%20%20%20retina_title_image_url%3A%20title_image_url%28retina%3A%20true%29%0A%20%20%20%20%20%20subtitle%0A%20%20%20%20%20%20link_text%0A%20%20%20%20%20%20href%0A%20%20%20%20%20%20background_image_url%0A%20%20%20%20%20%20credit_line%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)

Causes issues like:

```
  "errors": [
    {
      "message": "Expected a value of type \"HomePageHeroUnitMode\" but received: LEFT_DARK"
    },
    {
      "message": "Expected a value of type \"HomePageHeroUnitMode\" but received: LEFT_LIGHT"
    },
    {
      "message": "Expected a value of type \"HomePageHeroUnitMode\" but received: LEFT_DARK"
    },
    {
      "message": "Expected a value of type \"HomePageHeroUnitMode\" but received: LEFT_DARK"
    },
    {
      "message": "Expected a value of type \"HomePageHeroUnitMode\" but received: LEFT_LIGHT"
    }
  ],
```

A quick look inside the enum shows they're defined as:

```
const HomePageHeroUnitType = new GraphQLObjectType({
  name: "HomePageHeroUnit",
  fields: {
    ...GravityIDFields,
    cached,
    mode: {
      type: new GraphQLEnumType({
        name: "HomePageHeroUnitMode",
        values: {
          LEFT_DARK: {
            value: "left white",
          },
          LEFT_LIGHT: {
            value: "left black",
          },
          CENTERED_DARK: {
            value: "center white",
          },
          CENTERED_LIGHT: {
            value: "center black",
          },
          RIGHT_DARK: {
            value: "right white",
          },
          RIGHT_LIGHT: {
            value: "right black",
          },
        },
      }),
      resolve: ({ type, menu_color_class }) => {
        return type.toLowerCase() + " " + menu_color_class.toLowerCase()
      },
    },
```

it looks like in turning on stitching, the value being passed into the [completeLeafValue](https://github.com/graphql/graphql-js/blob/fed3ef58fde674fa96d79879eb4dfc24a0ba1db0/src/execution/execute.js#L1005-L1023)  is the actual enum name `LEFT_DARK` _not_ the value `left white` (sidenote: they're backwards?)

### PR DESCRIPTION
**Pull request by orta**
Fixes #836 

screen shot 2018-02-16 at 3 44 16 pm

### CODE REVIEW

**Comment by orta** [comment]
Aha, figured out my issue when trying to figure it out - think we need to apply this: https://github.com/artsy/metaphysics/commit/38be9dc2440ea162844883bee7945dd3dbee0900

To the stitched graphql schema also

**Comment by orta** [comment]
We found issues with the merged schemas showing `Reserved by GraphQL introspection.\n\nName \"__id\" must not begin with \"__\", which is reserved` when updating.

It looks like graphql-tools needs to be updated to allow passing graphschema options - there was a PR adding the ability to do that made an hour ago: https://github.com/graphql/graphql-js/pull/1249

To continue, we need to:

 - wait on a graphqljs release
 - need to add a pr to graphql-tools to support passing build options

**Comment by orta** [comment]
I fixed this in my node modules, by removing the error reporting, and it worked fine, so  Think this is our last blocker before we start thinking about problems

**Comment by joeyAghion** [comment]
Looks like [2.22.0](https://www.npmjs.com/package/graphql-tools) is out. Does this mean this work is unblocked?

**Comment by orta** [comment]
Yep, I think so

**Comment by mzikherman** [comment]
Closing in favor of https://github.com/artsy/metaphysics/pull/979

**Pull request closed without merging**
