### PR TITLE
Remove mentions of Semaphore

### PR DESCRIPTION
**Pull request by jonallured**
Shhh, let's pretend this never happened.

### CODE REVIEW

**Comment by alloy** [comment]
Hahaha, the CI that shall no longer be named.

Looking at [the GH preview](https://github.com/jonallured/metaphysics/blob/d3f1c620f32196eb2dd4a99f18f56856d9d79491/README.md), I’m seeing some malformed markdown. Is that just a limitation of GH’s preview or a legit issue?

**Comment by jonallured** [comment]
Whoa I see that too, so weird! I just copy/pasted from Bearden:

https://github.com/artsy/bearden/blob/master/README.md

```md
# Bearden [![CircleCI][badge]][circleci]

# Metaphysics [![CircleCI][badge]][circleci]
```

And it works over there. I honestly don't know! Up for merging and we'll see what happens?

**Comment by alloy** [comment]
Totes 👍 I like living dangerously.

**Comment by alloy** [comment]
[](https://media0.giphy.com/media/ohMtDzrhrWgnK/giphy.gif)

**Pull request merged**
