### PR TITLE
[ci] Re-enable danger, but only print failures to stdout

### PR DESCRIPTION
**Pull request by alloy**
Reverts #1739

### CODE REVIEW

**Comment by alloy** [comment]
```
Skipping Danger due to this run not executing on a PR.
```

Hrmm. Unsure why this is 🤔

**Comment by alloy** [comment]
Going to create a new PR to see if enabling the “only build pull-requests” CircleCI setting fixes this.

**Comment by alloy** [comment]
It turns out that danger insists on having an API key, as it needs to be able to grab PR metadata and doing so without API key would lead to rate-limiting quickly. So this doesn’t appear to be an option 😞 

```
metaphysics_1            | $ /app/node_modules/.bin/danger ci --text-only
metaphysics_1            | The DANGER_GITHUB_API_TOKEN/DANGER_BITBUCKETSERVER_HOST environmental variable is missing
metaphysics_1            | Without an api token, danger will be unable to comment on a PR
metaphysics_1            | Error:  Error: Cannot use authenticated API requests.
metaphysics_1            |     at Object.getPlatformForEnv (/app/node_modules/danger/distribution/platforms/platform.js:51:11)
metaphysics_1            |     at Object.<anonymous> (/app/node_modules/danger/distribution/commands/ci/runner.js:81:57)
metaphysics_1            |     at step (/app/node_modules/danger/distribution/commands/ci/runner.js:32:23)
metaphysics_1            |     at Object.next (/app/node_modules/danger/distribution/commands/ci/runner.js:13:53)
metaphysics_1            |     at fulfilled (/app/node_modules/danger/distribution/commands/ci/runner.js:4:58)
metaphysics_1            |     at process._tickCallback (internal/process/next_tick.js:68:7)
metaphysics_1            |     at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
metaphysics_1            |     at startup (internal/bootstrap/node.js:285:19)
metaphysics_1            |     at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

**Comment by joeyAghion** [comment]
Re. needing a key to avoid rate-limiting when pulling PR metadata, is that an intrinsic requirement, or just a choice in Danger? On the surface, it seems like requesting a single open source PR's metadata shouldn't encounter limits.

**Comment by alloy** [comment]
A choice in Danger, as I understand it.

**Comment by alloy** [comment]
I guess we could try to see how fast we run into it by applying a patch-package path to danger that disables this check?

**Pull request closed without merging**
