### PR TITLE
@orta => Dont crash when just deathday is provided

### PR DESCRIPTION
**Pull request by mzikherman**
We were being defensive about missing nationalities, birthdays and deathdays- except it would still crash if _just_ the deathday was provided :(

Fixes errors like: https://rpm.newrelic.com/accounts/1147389/applications/10782493/traced_errors/a83a7f90-c78b-11e6-972d-f8bc124256a0_0_7913

### CODE REVIEW

**Comment by orta** [comment]
oh - the bot worked

**Comment by orta** [comment]
screen shot 2016-12-21 at 10 19 46 am

**Comment by orta** [comment]
nice one

**Comment by alloy** [comment]
Can we take this time to also rename the 'formatted_bday' variable? Because it contains more than just bday by now.

**Comment by mzikherman** [comment]
Oo i didn't realize the bot was real-time like that. Here I am typing `list` in the window every hour :(

**Pull request merged**
