### PR TITLE
Switch organization to be an array

### PR DESCRIPTION
**Pull request by ashkan18**
Once https://github.com/artsy/diffusion/pull/185 is merged and deployed, this will catch up with that change.

# Selfie

image

### CODE REVIEW

**Comment by mzikherman** [comment]
@ashkan18 this is the first occurrence in the wild of the new Peril rule!

Basically, this is a breaking change with the version of the MP V2 schema which is currently in Force (thru Reaction). So while this might not actually be used, and MP gets deployed, and everything is fine...what will happen the next time _Force_ goes to get deployed?

That deploy will fail, since the schema present will be incompatible with the MP prod schema. Which will require the deployer to go to Reaction, bump the schema, update Force, wait for CI, etc.

So, if this PR gets merged w/ a breaking change, you should go to Reaction and bump the schema :)

**Comment by ashkan18** [comment]
ah, good point! i'll keep that argument and deprecate it and add a new `organizations` plural. thanks for the 👀

**Comment by ashkan18** [comment]
@mzikherman for now i kept that value and added new `organizations` one as a separate thing. 2 questions:
1) looks like arguments can't be deprecated, is that correct?
2) how can we remove the old argument eventually then?

**Comment by mzikherman** [comment]
Interesting! Yea, looks like input arguments can't be deprecated/that's not in the spec yet.

In that case you can just remove or alter it here (up to you). The only thing is that Force's production deploy check will eventually fail (since this is a 'breaking' change). So as a workflow item you should update the schema in Reaction -> Force soon after this PR is merged (vs. the deployer of Force needing to do that possibly days from now).

This Peril comment is only a warning, so it's fine to merge!

**Comment by sepans** [comment]
🙌 merging.

**Pull request merged**
