### PR TITLE
fix(ONYX-72): use authenticatedArtistLoader to return custom artist data

### PR DESCRIPTION
**Pull request by dariakoko**
Co-authored-by: Sultan Al-Maari <sultan.al-maari@artsymail.com>

This PR resolves [ONYX-72]

| custom artist with the authenticatedArtistLoader | custom artist without the authenticatedArtistLoader | public artist |
| --- | --- | --- |
|  image | image | image |

[ONYX-72]: https://artsyproduct.atlassian.net/browse/ONYX-72?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MounirDhahri — APPROVED** [review]
LGTM
I will also tag @mzikherman here in case the unauthenticated artist loader has a behaviour that I am unfamiliar with that differs it from the authenticated artist loader

**Review by olerichter00 — APPROVED** [review]

**Comment by MounirDhahri** [comment]
Thanks Matt!

**Comment by dariakoko** [comment]
Just tested your PR, works perfectly, thanks @mzikherman!

**Comment by dariakoko** [comment]
Closing because not needed

**Pull request closed without merging**
