### PR TITLE
Refactor module paths

### PR DESCRIPTION
**Pull request by damassi**
Similar to Force and Prediction, this PR refactors our module imports to take advantage of https://github.com/tleunen/babel-plugin-module-resolver, which allows us to avoid the node.js path plague (`../../../`). 

While updating, after each file change the dev server rebooted and static module resolution ensured that there were no breaks, and all of our Jest tests pass. 

The rule of thumb for updating a path is: 
- If going backward `../../*`, make absolute
- If going forward or importing a module that exists alongside, keep relative (`./foo`, `./utils/foo`)

### CODE REVIEW

**Comment by damassi** [comment]
Oh no, wasn't aware of that, but will do.

**Comment by damassi** [comment]
@alloy Tested via 
```sh
yarn heroku-postbuild 
node_modules/.bin/forever -c "node -r dotenv/config --max_old_space_size=960" build/index.js
```
And everything works great.

**Comment by alloy** [comment]
Ace 🙆‍♂️

**Comment by orta** [comment]
Do we want this style in Emission too then?

**Comment by alloy** [comment]
@orta Yeah, everywhere, there were just some issues when we tried to apply it in reaction-force previously

**Comment by alloy** [comment]
⚠️ In case you’re running into test failures, since this change, try clearing jest’s cache: `yarn test -- --no-cache`

**Pull request merged**
