### PR TITLE
Add a description to the is_display_auction_link

### PR DESCRIPTION
**Pull request by orta**
more docs is more docs

### CODE REVIEW

**Comment by alloy** [comment]
I guess this answers my question here https://github.com/artsy/emission/pull/372#discussion_r84259124 then, but if this is what it signifies than it should have been called something like `should_display_auction_results` imo.

**Comment by orta** [comment]
Yep, it should

**Comment by orta** [comment]
This temrinology comes from gravity https://github.com/artsy/gravity/blob/4bc60e56515bd9222828e4b3a4ffb0adbc16b147/app/models/domain/artist.rb#L301-L302

**Comment by alloy** [comment]
Yup, my point is more that at some point somebody should raise an issue about the ambiguity in our APIs, rather sooner than later.

**Pull request merged**
