### PR TITLE
@cavvia => Update artwork pageview data

### PR DESCRIPTION
**Pull request by mzikherman**
New S3 file converted here to JSON.

Curious how often we want to be updating this data? If it's weekly, for an indefinite period, we may want to rework the process to avoid massaging the CSV -> JSON, PR'ing in Metaphysics, etc.

### CODE REVIEW

**Comment by joeyAghion** [comment]
This is... less than ideal, right?

I understand that it's a test, but is there a way we can avoid mixing the data into this layer (and into source control in perpetuity)? Maybe use S3 as a back-end that MP proxies to as necessary?

**Comment by mzikherman** [comment]
> This is... less than ideal, right?

Sure, but this was the compromise we settled on. We didn't want to build any backend or proper storage for this, since it was static data that might only exist temporarily. Loading (safely, upon boot, possibly controlled via a feature flag) from S3 seems like a better solution than this, certainly, but that's just not what we wound up implementing at the time.

I also wasn't aware we would be updating the data...I thought it would be static for the duration of the test. That obviously makes the S3 solution more compelling.

Live and learn! In hindsight the S3 solution is probably better, we can have a work item to convert that here (but at this point I'd be inclined to wait for the test to conclude), but certainly the next similar task should be done that way.

**Comment by cavvia** [comment]
@joeyAghion This is definitely going away when the test ends, so there's no danger of it living in source control in perpetuity. Agreed S3 is better. We will probably need to update this 1 or 2 more times before the end of the test.

**Comment by mzikherman** [comment]
Merging this.

**Pull request merged**
