### PR TITLE
@joeyAghion => [Patch] Add specs around variable coercion patch

### PR DESCRIPTION
**Pull request by mzikherman**
Trying to write a spec for recent patches, and noticed we have this handy integration spec.

However, it is guarded to  _only_ run on CI, and I can't get it work locally.

I'm pretty skeptical this is being run on CI...

### CODE REVIEW

**Comment by mzikherman** [comment]
Welp, CI is definitely not running this :)

**Comment by joeyAghion** [comment]
An unrunnable spec!

**Comment by mzikherman** [comment]
This is ready to go w/ tests re-enabled!

**Comment by mzikherman** [comment]
In terms of re-enabling this spec: it was pretty recently added (this year!), and https://github.com/artsy/metaphysics/pull/1463#discussion_r251540540 talks about the non-performance of running with `--watch`.

I'm not sure how often people are actually running jest with `--watch`, and it seems like it's kind of indirect to try to avoid running in that mode, vs. locally in test mode.

I'm also...not 100% sure why it _wasn't_ running in CI, since the `CI=true` ENV var should be set by Circle, but I'm not sure it's even worth debugging that if we just reenable them.

**Comment by joeyAghion** [comment]
🙇

**Pull request merged**
