### PR TITLE
@sweir27 (cc @acjay): Update Causality JWT logic

### PR DESCRIPTION
**Pull request by craigspaeth**
This updates the JWT logic to split the path down it's 4 separate ways...

1. Any logged out users default to "observer" role
2. A logged in user specifying PARTICIPANT gets a "bidder" role if registered
3. A logged in user specifying PARTICIPANT gets a "observer" role if *not* registered
4. An admin specifying OPERATOR gets "operator" role or "unauthorized" if not admin

### CODE REVIEW

**Comment by craigspaeth** [comment]
cc @orta I noticed you updated the logic to have BIDDER || OBSERVER default to "observer" if not registered. This introduces specifying PARTICIPANT instead [see relevant thread](https://artsy.slack.com/archives/auctions-dev/p1464031522002529)

**Comment by sweir27** [comment]
👍 Thanks!!

**Comment by orta** [comment]
Thanks, applied on our end

**Comment by acjay** [comment]
🙌

**Pull request merged**
