### PR TITLE
Adds require_bidder_approval field to Sale schema.

### PR DESCRIPTION
**Pull request by ashfurrow**
This is needed for an Eigen request.

### CODE REVIEW

**Comment by sweir27** [comment]
This looks fine! May I ask what eigen needs this field for?

**Comment by ashfurrow** [comment]
That's a good question, it just came up as a required field in our bidder model. I'll get back to you about more specifics.

**Comment by ashfurrow** [comment]
We use it to have a "pending registration" state for users after they register for a sale.

**Comment by sweir27** [comment]
Closing this per our discussion!

**Pull request merged**
