### PR TITLE
Move has_message to @GET conversations

### PR DESCRIPTION
**Pull request by ashkan18**
from @GET conversations/:id

### CODE REVIEW

**Comment by alloy** [comment]
If possible it would be nice to record a few more details around this change here. I assume we were just sending a param to the wrong endpoint? What does the param do?

**Comment by orta** [comment]
Re: #867 - I applied it to the individual endpoint instead of the index - that flag stops pre-radiation conversations being passed to metaphysics

**Comment by ashkan18** [comment]
Conversations created pre-radiation don't have `initial_message` and also don't have `radiation_conversation_id` in CMS we show them in inbox but when we click on them, since technically there are no messages, we show them the inquiry with a message below it, saying this conversation pre-dates artsy's conversation (or something like that) and they can't take any action on these conversations (no reply, dismiss or anything).

**Comment by alloy** [comment]
Gotcha, thanks!

**Pull request merged**
