### PR TITLE
@sweir27: Expose buyer's premium

### PR DESCRIPTION
**Pull request by craigspaeth**
This exposes a sale's buyer's premium in MP...

image

In Gravity there's all this other data other than `schedule` that we don't use, but I wanted to check with you that I'm not overlooking something useful in here... e.g. Why would we ever need to know the `name` or `currency` aren't those always the same as the auction itself?

image

We need this data to render UI's like this that explain the buyer's premium policy...

image

### CODE REVIEW

**Comment by sweir27** [comment]
I think the other data is used when creating copy for invoices (and maybe elsewhere as well). I cannot see a reason why we shouldn't default to the sale's currency when displaying this, but from your sample output it looks like metaphysics might be defaulting to `'$'` here, even though the BP and sale for koller is in CHF

**Comment by craigspaeth** [comment]
😛  good catch! Yeah I noticed that too—looking at a fix rn. Otherwise this should be good?

**Comment by sweir27** [comment]
Yep looks good besides that!

**Comment by craigspaeth** [comment]
Ok updated to pull the currency from the sale

image

**Comment by sweir27** [comment]
👍

**Comment by acjay** [comment]
I would be careful with using the currency from the sale. They _should_ definitely be the same (which should really be validated), but if they aren't, I'm not sure we'd want to make the mistake of adapting a buyer's premium into the wrong currency. In that case, I think we'd be better off quietly failing in a way that would notify somebody and clients would do something intelligent to cover for the missing data.

**Comment by acjay** [comment]
Also, additional Metaphysics request: a way to get the increment strategy name. It wasn't there so I'm just defaulting to "default".

**Pull request merged**
