### PR TITLE
Add request condition report mutation

### PR DESCRIPTION
**Pull request by dblandin**
Add a GraphQL mutation enabling an authenticated user to request a condition report for an artwork in a sale.

**Request**

```graphql
mutation {
  requestConditionReport(input: { saleArtworkID: "example-123"}) {
    clientMutationId
  }
}
```

jira :lock:: https://artsyproduct.atlassian.net/browse/AUCT-742 / [AUCT-742]

[AUCT-742]: https://artsyproduct.atlassian.net/browse/AUCT-742

### CODE REVIEW

**Comment by mzikherman** [comment]
Random question. It looks like this passes thru to an underlying endpoint in Gravity (https://github.com/artsy/gravity/pull/12698) which seems new-ish. Should this be a mutation in Gravity that's stitched in?

Not a blocker since we have lots of this kind of example around, and stitching _is_ deprecated by Apollo, but nevertheless, this seems like it should be pretty straightforward to stitch in from Gravity. It might not require any MP code besides the schema update, and then the Gravity mutation in place of the REST endpoint.

**Comment by dblandin** [comment]
> Random question. It looks like this passes thru to an underlying endpoint in Gravity (artsy/gravity#12698) which seems new-ish. Should this be a mutation in Gravity that's stitched in?

That sounds interesting! I haven't updated Gravity's GraphQL schema before but can definitely look into that!

**Comment by dblandin** [comment]
Opened a PR with that Gravity GraphQL implementation here: https://github.com/artsy/gravity/pull/12702

**Comment by dblandin** [comment]
Closing in favor of https://github.com/artsy/gravity/pull/12702

**Pull request closed without merging**
