### PR TITLE
@dzucconi: consignable flag on artist

### PR DESCRIPTION
**Pull request by 1aurabrown**
for https://github.com/artsy/force/issues/4825

### CODE REVIEW

**Comment by dzucconi** [comment]
I prefer any Boolean flags to be prefixed with `is_`, would be nice to deprecate the public flag above it in favor of an `is_` as well.

**Comment by 1aurabrown** [comment]
sure, i'm not sure where all the references to this endpoint with the `public` parameter are. can go through and do that at some point.

**Comment by dzucconi** [comment]
That's the thing about using GraphQL deprecation though—you don't need to know. You add a `deprecationReason` which then causes the field to stop showing up in GraphiQL as a valid field, but existing queries still resolve.

**Comment by 1aurabrown** [comment]
oooooo interesting!!!!!!!!!!

**Pull request merged**
