### PR TITLE
@yuki24 => Switch to float from int for budget question in /personalize

### PR DESCRIPTION
**Pull request by mzikherman**
Noticed some of these in prod: https://sentry.io/artsynet/metaphysics-production/issues/490033077/

I think theres an issue with recording the answer 'No Budget in Mind' currently.

### CODE REVIEW

**Comment by yuki24** [comment]
Ah thanks for catching that! We should probably stop using numbers that are too long in Force. I'll send a PR to update the value for 'No Budget'.

**Comment by yuki24** [comment]
Actually... since the budget data is stored in Gravity and there are conditionals like [this](https://github.com/artsy/force/blob/master/src/desktop/apps/pro_buyer/pages/complete/client/view.coffee#L87), I don't think we can just change Force without data migration. Maybe MP should use a type which length is longer.

**Comment by mzikherman** [comment]
> Maybe MP should use a type which length is longer.

Yea, I think that's what this, accomplishes, no? That was my intent.

**Comment by yuki24** [comment]
I'm not sure about JS or GraphQl, but in general, the length of `Float` (or any other number types like `Int`) depends on the OS, so it is not guaranteed it is always longer than 32 bits. `Float` also implies the need of CPU optimizations for math operations, which we don't need.

It seems like what's recommended is to use [the `String` type](https://github.com/graphql/graphql-js/issues/292), which I'm not sure about either.

**Comment by mzikherman** [comment]
How should we proceed?

I think this is safe to merge as it should work with everything as-is (and helps alleviate the current issue).

However, I'm with you that string for this is maybe the way to go. But, it seems like thats a breaking change to the currently deployed onboarding update?

**Comment by yuki24** [comment]
It seems that the length of `Float` is 53 bits. According to [the spec](http://facebook.github.io/graphql/October2016/#sec-Float) it (signed double‐precision fractional value) originates from the [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754) spec, which length is 53 bits. So I think this should be good to merge.

**Pull request merged**
