### PR TITLE
[Messaging] adds artworks to conversation type

### PR DESCRIPTION
**Pull request by l2succes**
This PR adds some missing fields to the conversations schema to support the Inbox view

screen shot 2017-05-29 at 5 30 38 pm

screen shot 2017-05-29 at 5 34 55 pm

### CODE REVIEW

**Comment by alloy** [comment]
Shouldn’t this be a ‘connection’ so Relay can paginate?

**Comment by l2succes** [comment]
@alloy yup, it needs to be a connection. Working on that now

**Comment by alloy** [comment]
Make note that reaction-force will need to be updated to query using this new schema.

Code looks good to me 👍 Merge on 💚

**Comment by l2succes** [comment]
@alloy Cool! I'll create a ticket to remember updating the query in reaction-force

**Pull request merged**
