### PR TITLE
@broskoski => Custom text for on hold works as well

### PR DESCRIPTION
**Pull request by mzikherman**
Oops forgot this, we want to blank the text for 'not for sale' works, and include the standard one for 'on hold'.

So:

sold: custom text
on hold/for sale: custom text (diff from sold)
not for sale: no text

### CODE REVIEW

**Comment by broskoski** [comment]
Use your lint roller, brah

**Comment by broskoski** [comment]
Otherwise LGTM

**Comment by mzikherman** [comment]
ugh gosh darn it

**Comment by mzikherman** [comment]
💚

**Comment by broskoski** [comment]
Wow MP tests are so much faster now.

**Pull request merged**
