### PR TITLE
Revert "chore: make my collection info node"

### PR DESCRIPTION
**Pull request by MounirDhahri**
Reverts artsy/metaphysics#5000
The id from my collection is not returning properly. Reverting this until we fix it.

### CODE REVIEW

**Comment by olerichter00** [comment]
> The id from my collection is not returning properly. Reverting this until we fix it.

Which id is it?

**Comment by MounirDhahri** [comment]
my collection id is available when I am testing from Insomnia, it's being printed but it's raising an error on my simulator. I reverted this to avoid potentially breaking something in prod.

**Comment by olerichter00** [comment]
Seems like MP returns `null` for `pageInfo` which shouldn't be `null`. Is this after refetching the connection?

**Comment by MounirDhahri** [comment]
As you see, in Insomnia it's working well. which leads me to believe we have an issue with something else that only showed up now
Screenshot 2023-05-10 at 11 43 32

**Comment by olerichter00** [comment]
You could compare the query in Insomnia with the query that Relay generates to see if there is a difference.

**Pull request merged**
