### PR TITLE
CSGN-327: Stitch in diffusion schema

### PR DESCRIPTION
**Pull request by jonallured**
This PR stitches in the diffusion GQL schema. It is about as basic as possible - it does not do anything to forward the auth, for example. Which means that the query actually fails because diffusion is setup with authentication but that's not this PR's problem!

I will follow up on this topic if a future PR - either relaxing diffusion's checks or improving this stitching code to properly pass auth creds over to diffusion.

https://artsyproduct.atlassian.net/browse/CSGN-327

/cc @artsy/csgn-devs

### CODE REVIEW

**Comment by damassi** [comment]
@jonallured - noticed some test failures. Might as well take this time to copy paste in a couple light tests / infra as seen in the causality PR.

**Comment by jonallured** [comment]
I've been poking at this again this morning and I can't figure out why CI and my local test runs don't match. Here's what I got:

```
Summary of all failing tests
 FAIL  src/integration/__tests__/integration.test.ts (15.42s)
  ● integration tests › doesn't include `extensions` by default

    expect(received).toBeFalsy()

    Received: {"requestID": "eb4ce2f0-eeb4-11ea-9bd3-ad7adbf62274", "requests": {"gravity": {"requests": {"artist/banksy": {"cache": true, "length": "N/A", "time": "0s 0.795ms"}}}}}

      85 |     expect(response.body.data).toEqual({ artist: { name: "Mr Bank" } })
      86 |     expect(response.statusCode).toBe(200)
    > 87 |     expect(response.body.extensions).toBeFalsy()
         |                                      ^
      88 |   })
      89 | })
      90 |

      at Object.<anonymous> (src/integration/__tests__/integration.test.ts:87:38)


Test Suites: 1 failed, 16 skipped, 285 passed, 286 of 302 total
Tests:       1 failed, 49 skipped, 3334 passed, 3384 total
Snapshots:   101 passed, 101 total
Time:        149.039s, estimated 169s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

One failure and it doesn't even seem related. The CI run claims to have 426 failed tests and 6 failed snapshots. I have 1 failing test and all my snapshots are passing. Any thoughts @damassi or @zephraph? 🤔

**Comment by damassi** [comment]
@jonallured  Will pull down the branch and give it a look in a sec

**Comment by jonallured** [comment]
Some chatter here, but @damassi figured it out - I was missing some required ENV vars in the test dotenv file.

https://artsy.slack.com/archives/CS3H1K4BD/p1599247425155100

**Pull request merged**
