### PR TITLE
#experimental split cache client to reader and writer clients

### PR DESCRIPTION
**Pull request by izakp**
Making an experiment to split cache reads and writes onto two separate clients, each with their own connection pools - in this way ensure that no `SET` or `DEL` commands can be interleaved with `SET` commands.

cc @acjay @alloy

### CODE REVIEW

**Comment by alloy** [comment]
Interesting! Is there an intrinsic problem you’re thinking of with interleaving them?

**Comment by izakp** [comment]
I want to rule out the possibility that our cache read latency is at all compounded by `GET` commands queued up behind `SET` commands (as we do an async `SET` for every `GET`).  Will instrument the number of slow cache reads / sec first.

Marking this as #experimental - will revert if it proves no performance benefit

**Comment by izakp** [comment]
See https://github.com/artsy/metaphysics/pull/1105

**Comment by izakp** [comment]
No observed change in cache latency or read timeouts.  Reverting in https://github.com/artsy/metaphysics/pull/1106

**Pull request merged**
