### PR TITLE
@mzikherman => Adds count to article's status resolve

### PR DESCRIPTION
**Pull request by kanaabe**
Thanks for catching this.

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Please assign someone to merge this PR, and optionally include people who should review.</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by kanaabe** [comment]
Hmm am i missing something? When i run `npm test` locally, everything passes.

**Comment by mzikherman** [comment]
I just rebuilt and it was fine, i think something blipped with Danger.

Merging, i see a couple other places where we're using the count of articles, I'll pr those to you in a sec.

**Comment by kanaabe** [comment]
🔮  thanks Matt! Next time I will notify #collector-gmv before changes like this to cover better ground.

**Comment by mzikherman** [comment]
no worries! all in a days work for changing a back-end API :)

**Pull request merged**
