### PR TITLE
Sync schema to reaction on update

### PR DESCRIPTION
**Pull request by damassi**
Following [recent work to sync changes to Eigen](https://github.com/artsy/metaphysics/pull/2288/), lets carry it on to Reaction 🥳 

Ran script locally and seemed to work great, but no actual changes to sync yet: 

Screen Shot 2020-04-09 at 3 48 28 PM

@ds300 - https://github.com/artsy/update-repo is seriously cool! Lets broadcast it.

### CODE REVIEW

**Comment by zephraph** [comment]
So w/ auto, we set up ssh keys via CircleCI directly. Circle has a way to automatically configure a repo with SSH keys for pushing to that repo. The caveat for that is that it's intended for the _same_ repo that CI is running against so it wouldn't be helpful in this case. 

If you're using an SSH key I believe you don't need a github token to push.

**Comment by ds300** [comment]
Ah i see. We do need both kinds if auth then, ssh for pushing and access token for creating the PR. So let's do what I said before and replace the repo-level ssh key in this job with a user-level key for `artsyit`.

**Comment by ds300** [comment]
ooooh I did some research and looks like you \*can\* push to a repo with a GH_TOKEN after all.

you just check out the repo with https as `https://<GH_TOKEN>@github.com/owner/repo.git`

So we can change `update-repo` to do that and then just merge this as-is  🙌 feel free to take that work on, otherwise I can get around to it on tuesday.

**Comment by ds300** [comment]
🎉 https://github.com/artsy/reaction/pull/3390

**Comment by damassi** [comment]
Yesssss

**Pull request merged**
