### PR TITLE
Set keyword_match_exact when keywords are set on a Kaws collection.

### PR DESCRIPTION
**Pull request by SamRozen**
[[[GROW-1005]](https://artsyproduct.atlassian.net/browse/GROW-1005)](https://artsyproduct.atlassian.net/browse/GROW-1005)

When fetching collections info from Kaws, set keyword_match_exact parameter to true if collections has keywords for artwork filters.

[GROW-1005]: https://artsyproduct.atlassian.net/browse/GROW-1005

### CODE REVIEW

**Comment by SamRozen** [comment]
@l2succes I've been able to test manually that I request from GraphiQL a collection that has keywords in the query, it sets the right GravityOptions in filter_artwork.ts (line 328). But I don't know how to test further in dev environment. I'm curious to get your take on what else we should do here.

**Comment by SamRozen** [comment]
Definitely checking this https://staging.artsy.net/collection/kaws-snoopy would let us know if it's working or not, once it's deployed to staging.

**Comment by l2succes** [comment]
@SamRozen The easiest way to test this would be to merge this and verify that it works in staging.
Let me pull that branch and verify it locally for you. I'll let you know how it looks for the collection you mentioned

**Comment by SamRozen** [comment]
@orta how do you feel about merging this for now and then we can go back to the unit test later?

**Comment by mzikherman** [comment]
This test (pended with `it.skip`) makes actual calls to KAWS during tests.

Subsequent to this PR, another developer (and myself), unpended the tests (b/c there was no comment or TODO/reason in the file about why they were pended), and b/c they passed, we left them as such.

Minor nit- in the future, we should put essential messages/comments like that, in the actual file. It can be a `//TODO` or `//FIXME` or whatever. I'm realizing now that it was specified in the commit message by @SamRozen ...but many of us don't look thru commit history too often. A comment directly in the file feels more appropriate and would have saved some confusion.

**Comment by SamRozen** [comment]
Good call, thanks for the feedback @mzikherman. I should have indeed added a //TODO.

**Pull request merged**
