### PR TITLE
feat: Add me.labFeatures

### PR DESCRIPTION
**Pull request by bhoggard**
https://artsyproduct.atlassian.net/browse/CX-714

@ansor4, wanted to make sure this approach makes sense to you. We would like to start using an array, so that we don't have to add a new field to `me` every time we add a new lab feature.

### CODE REVIEW

**Comment by ds300** [comment]
this seems like it's compatible with the graph-based feature toggles @ansor4 was talking about. We would just need to flatten the graph into a set and put it in this array without affecting consumers. But maybe there's a more forward-thinking api we could adopt already, so I'll hold off until @ansor4 has a chance to comment.

**Review by ds300 — APPROVED** [review]
🙌

**Review by MounirDhahri — APPROVED** [review]

**Comment by MounirDhahri** [comment]
🎉

**Review by ansor4 — APPROVED** [review]
This makes sense to me! Agree with @ds300 that we would want to flatten the underlying feature graph into an array, clients shouldn't need to know how features are structured.

**Pull request merged**
