### PR TITLE
fix(artwork lists): collection artworks pagination

### PR DESCRIPTION
**Pull request by anandaroop**
https://artsyproduct.atlassian.net/browse/FX-4593

Adds missing `page` arg for `collection.artworksConnection`

```graphql
{
  me {
    collection(id: "42427e8172616975e8004242") {
                         👇🏽
      artworksConnection(page: 2) {
        edges {
          node {
            slug
          }
        }
      }
    }
  }
}
```

### CODE REVIEW

**Comment by dimatretyak** [comment]
I removed the `size` argument as it duplicates the functionality of the `first` argument

**Review by dimatretyak — APPROVED** [review]

**Comment by anandaroop** [comment]
Thanks for merging, but I'm interested in the `size` thing —

My understanding is that `page` + `size` go together for "traditional" pagination, whereas `first` + `after` and `last` + `before` go together for [cursor-based connection pagination](https://www.apollographql.com/blog/graphql/explaining-graphql-connections/).

So `size` and `first` don't really represent the same concept.

In fact many if not most of our connections support both styles of pagination, and thus accept `size` as well as `first`?

Examples [here](https://github.com/artsy/metaphysics/blob/99a12ac1c449379f128e5ad01794f64437cadb7a/_schemaV2.graphql#L1315-L1323), [here](https://github.com/artsy/metaphysics/blob/99a12ac1c449379f128e5ad01794f64437cadb7a/_schemaV2.graphql#L1444-L1477) and [here](https://github.com/artsy/metaphysics/blob/99a12ac1c449379f128e5ad01794f64437cadb7a/_schemaV2.graphql#L9428-L9431)

My 2¢ is that we should add that back in, what do you think?

**Comment by dimatretyak** [comment]
@anandaroop yes, maybe you're right. I have nothing against `size'. it just seemed like it wasn't necessary to use it here

**Comment by dimatretyak** [comment]
> In fact many if not most of our connections support both styles of pagination, and thus accept size as well as first?

to tell the truth, it seemed to me that the `size` argument is not particularly used and for this reason I decided to remove it

image

**Comment by damassi** [comment]
Size is a not-too-connection-y concept which is a bit confusing when mixed with `first`, imo. If `size` is being used anywhere at the field level its likely tech debt.

**Comment by anandaroop** [comment]
Yeah agree that neither `size` should not be mixed with `first` — but nor should `page` be mixed with `first` either.

If you specify `page`, how else would you control the page size without a `size` argument?

**Comment by anandaroop** [comment]
Oh h/t @dzucconi for writing this up:

https://github.com/artsy/metaphysics/blob/main/docs/pagination.md#2-pageable-arguments

We can still consider this a best-practice reference right?

**Comment by dzucconi** [comment]
Yep, you'd want to include `size` if you're including `page`. We can't do unions in input types unfortunately, so yes: technically you can pass both and technically that's incorrect: don't do that obviously.

**Comment by dzucconi** [comment]
And `size` is not tech debt. `first` is just a different concept for cursor based arguments.

You wouldn't mix `first` and `last`, for instance too btw.

**Comment by damassi** [comment]
Well I mean, its typically not used with our connection-based approaches. When we utilize pageable and the helper and pass in `first`, etc, its converted to size which we then pass to gravity. It is uncommon to see it actually used at the field level, and that's what i mean about it being debt; its old and perhaps misconfigured for our current intents and purposes. Do correct me if I'm wrong here!

**Comment by dzucconi** [comment]
We don't actually do real cursor based pagination. We support numeric pages. `page` and `size` are the natural arguments to support that. `page` and `first` does not make any sense.

**Comment by dzucconi** [comment]
And it's not uncommon in our schema either, every piece of UI that uses numeric pages is using `page` + `size`

**Comment by anandaroop** [comment]
Going back to the use case that originated this ticket, we currently see examples like this in client code:

https://github.com/artsy/force/blob/6aad98f3bbf84b40f4afd9731d36ae8ee08218f9/src/Apps/CollectorProfile/Routes/Saves2/Components/SavesArtworks.tsx#L107

Two points:

- To me that is an improper combination of `page` and `first` — we mixing two different pagination metaphors there
- Not clear if this should be doing page+size or first+after as a best-practice — I don't think we are nearly consistent about this across the codebase

**Comment by dzucconi** [comment]
Personally: I'd find it a lot more annoying to have to fetch the page cursors, associate those with the numeric pages, pull out the correct cursor on click and query param just so I can use `first/after`, when I could just use `page/size` and not have to think about that. I see no problem with supporting both.

**Comment by dzucconi** [comment]
And despite it being 'incorrect' to use `size/first` interchangeably.... it also doesn't matter when both are supported.

**Comment by anandaroop** [comment]
Hmm but are they really interchangeable? I guess if you are on page 1 of an unchanging list then yes, but otherwise the point of first/after cursor pagination is to be resilient to changing lists. 

I recognize it may "just work" most of the time, I just want to save myself from a footgun by keeping the two pagination metaphors nice and separate.

**Comment by dzucconi** [comment]
first after isn't resilient to this because they aren't real cursors though.

**Comment by anandaroop** [comment]
Ah, yeah that is an important point

Okay, moving this to #graphql-yelling

Thanks for all the input though, very helpful.

**Comment by mzikherman** [comment]
We support + prefer the 'proper' connection-style arguments of `first` and `after`. Let's not even think about `last` and `before` b/c i don't think we do 'backwards' scrolling anywhere, or we can relegate that to a more niche mobile-specific sitation.

So basically, use `first` and `after` almost everywhere/always.

There's one use-case where we _do_ want to support `page` and `size` as connection-level arguments to a connection. Whether a little custom validation needs to be written that checks you are using either/or style, for a connection that supports both, would be gravy.

The reason _some_ connections might want to support `page` and `size` is to allow a user to load an arbitrary page for the first time. This is exclusively for web, and basically handles someone sharing a link of the form `?page=10`. If your connection isn't going to be used in that context you can stay with `first`/`last`.

**Comment by dzucconi** [comment]
Here's a question: why even bother supporting `first` and `after`?

**Comment by mzikherman** [comment]
We don't have to, really. I do recall some (early) thing with Relay where it straight up complains if you don't provide some connection-approved arguments to a connection (or maybe the outdated lib we use in MP that brings some Relay/connection helpers).

**Comment by mzikherman** [comment]
One more advantage of using `first/after` is that it's opaque to the client and _if we ever changed that implementation and was more cursor-like_ clients may continue to work seamlessly.

However, given that we've not ever done that, I'm willing to say that's a purely hypothetical advantage.

**Comment by damassi** [comment]
+1 in regarding Relay and graphql idioms. The compiler is finnicky, still.

**Pull request merged**
