### PR TITLE
@joeyAghion => Reimplement is_in_auction to move away from ElasticSearch

### PR DESCRIPTION
**Pull request by mzikherman**
Depends on query param format being discussed in https://github.com/artsy/gravity/pull/10546. Code talks = +1 for `sale_ids`!!

### CODE REVIEW

**Comment by mzikherman** [comment]
cc @cavvia this also depends on running the migration in https://github.com/artsy/gravity/pull/10537 (I can take that).

**Comment by cavvia** [comment]
:+1: I'm guessing this is the big one and `is_biddable` is only called within the auction context?  In any case I'm looking forward to cutting Gravity throughput by 20-30%!

**Comment by mzikherman** [comment]
> 👍 I'm guessing this is the big one and is_biddable is only called within the auction context? In any case I'm looking forward to cutting Gravity throughput by 20-30%!

Apparently `is_biddable` is used in list views too: https://github.com/artsy/force/blob/15c372159f40111ff12415681f21e1184cd10c6b/components/artwork_metadata_stub/queries/contact.coffee#L6-L7

**Comment by mzikherman** [comment]
And updated with `is_biddable` update as well. 

🍏

**Comment by mzikherman** [comment]
I also have `is_buy_nowable` ready to go, but it's really these two that are the big offenders since they're used even in artwork list views.

**Comment by mzikherman** [comment]
Bump @joeyAghion it's a new week should me merge/QA/mocktion?

**Pull request merged**
