### PR TITLE
@orta => Add ids to sales

### PR DESCRIPTION
**Pull request by eessex**
First Metaphysics PR 🎈 

Following up on pairing yesterday -- adds ids type to sales schema, and updates resolver to use `id` rather than `ids` (to stay in accordance with Gravity).

One thing I noticed is that this file is not yet tested, and many of the plural endpoints are not.  Tried a few of the testing models laid out in the schema folder but kept getting the error `Error: getaddrinfo ENOTFOUND api.artsy.test api.artsy.test:443` -- am I just missing an env var, or maybe this is another pairing opportunity?

### CODE REVIEW

**Comment by orta** [comment]
Yep this looks 👍

**Comment by orta** [comment]
The testing issue is likely because it's not using a gravity dataloader, I'm happy to merge this PR, and then we can pair on switching it over separately?

**Comment by orta** [comment]
( [docs on dataloaders](https://github.com/artsy/metaphysics/blob/master/docs/dataloaders.md) )

**Comment by eessex** [comment]
Docs on dataloaders are useful, probably a good idea to implement these when we pair!

**Pull request merged**
