### PR TITLE
@alloy: Use forever and max_old_space size to cap memory usage

### PR DESCRIPTION
**Pull request by craigspaeth**
Adds the --max_old_space_size flag to cap memory usage in Heroku, see https://github.com/nodejs/node/issues/3370. Also added forever for good measure to restart on crashes.

### CODE REVIEW

**Comment by alloy** [comment]
In Slack you had pointed me to [the Makefile](https://github.com/artsy/force/blob/4ec3c0dd84fcab4cd7ce64e1408d74b845634df5/Makefile#L21), why is this PR different?

**Comment by alloy** [comment]
CI is 🔻 regarding installation of yarn. Does it need a rebuild without cache or something?

**Comment by alloy** [comment]
I also don’t see an update to the `yarn.lock` file, you should check-in those changes.

**Comment by craigspaeth** [comment]
Oh right, I forgot we're using Yarn now. Will update.

We used a Makefile in Force b/c that was one of the popular ways to do it at the time Force was born. Nowadays it's more common to just use the package.json `scripts` field like we, mostly, do here. The only other thing we're also using here is Foreman + Procfiles to load a .env file and run different commands for dev/production. FWIW we can further consolidate this to just a package.json file by using [dotenv](https://github.com/bkeepers/dotenv).

... so many finicky build tool ideas in Node land.

**Comment by alloy** [comment]
Ooowww… It’s totally my bad, I didn’t realise I was looking at Force’s codebase, not metaphysics 😞 Thanks for clearing that up!

**Comment by alloy** [comment]
@orta Do you have any ideas from the top of your head about this CI failure re yarn installation?

**Comment by orta** [comment]
Fixed 👍

**Comment by craigspaeth** [comment]
Thanks Orta!

**Pull request merged**
