### PR TITLE
@xtina-starr => [Notifications] added artist href to notifications fields

### PR DESCRIPTION
**Pull request by sarahscott**
Adds artist href so we can route to the notification's artist.

### CODE REVIEW

**Comment by mzikherman** [comment]
Is there a reason to not use the existing `artworks` -> `artists` link?

ie:

```
node {
  artworks {
    artists {
      href
....
```

**Comment by sarahscott** [comment]
I tried but it was returning `null`, maybe because [we generate the url in mp?](https://github.com/artsy/metaphysics/blob/master/schema/artist/index.js#L375)

**Comment by sarahscott** [comment]
Oh do you mean use that in the client instead of generate it in metaphysics?

**Comment by mzikherman** [comment]
Yea, exactly. You can also pass `shallow: true` into `artists` (`artists(shallow: true) { ...`) to avoid re-fetching artists (since all you want is their slug which you already get).

screen shot 2017-04-07 at 10 53 38 am

Basically this example ^ will get you the hrefs with no additional call. Is it possible to use this shape?

**Comment by sarahscott** [comment]
Yeah that looks good 👍

**Comment by xtina-starr** [comment]
@sarahscott if you are going with @mzikherman suggestion is this PR still need or should it be closed? I'm mostly wondering it the image is still needed.

**Comment by sarahscott** [comment]
It can be closed! I moved the Image field up so it would be alphabetized but it'll still be there if I close this.

**Pull request closed without merging**
