### PR TITLE
feat: Add pagination functionality to myCollectionConnection

### PR DESCRIPTION
**Pull request by olerichter00**
## Description

This change is needed to make pagination for My Collection work in Force. I just used the same helper we already [use for saved artworks](https://github.com/artsy/metaphysics/blob/0f90d50899db09d0ca63f584b0a5c3c01d438e2a/src/schema/v2/me/savedArtworks.ts#L76).

### CODE REVIEW

**Review by MounirDhahri — COMMENTED** [review]
@olerichter00 this looks good to me, I only have one question before approving. This won't break any existing functionality on Eigen right?

**Comment by olerichter00** [comment]
Exactly, this should break pagination in Eigen. I'll double-check after this is deployed on staging 🤞

**Comment by olerichter00** [comment]
My mistake. I meant: This should **not** break Eigen :)

**Comment by MounirDhahri** [comment]
ah cool 👍

**Pull request merged**
