### PR TITLE
@l2succes => Invoice implements NodeInterface (for easier re-fetching)

### PR DESCRIPTION
**Pull request by mzikherman**
I'm working on re-fetching a given Invoice (once a payment notification is received). I _think_ this may make it easier to do that, but I'm still messing around.

### CODE REVIEW

**Comment by mzikherman** [comment]
Gonna merge, pretty innocuous.

**Comment by alloy** [comment]
You need to add the invoice module to this list https://github.com/artsy/metaphysics/blob/1d24eb4b2cc3b3db656f5dbea100bb085256b214/schema/object_identification.js#L37-L49 for the type to be queryable through the root `node` field.

**Comment by mzikherman** [comment]
Doh!

I didn't actually need `NodeInterface` (but left it since it was harmless), will update.

**Comment by l2succes** [comment]
👌🏿

**Pull request merged**
