### PR TITLE
refactor(homeView): organize directory structure

### PR DESCRIPTION
**Pull request by anandaroop**
Part 1 of 2, not controversial I hope — just takes our big blob of files and organizes them into folders.

(Part 2 will be a little more drastic, so I'll split that out into a [separate PR](https://github.com/artsy/metaphysics/pull/6010) for discussion)

<table>
  <tr><td><b>Before</b>: most things sitting at the root</td><td><b>After</b>: resolvers, sections, helpers organized into folders</td></tr>
  <tr>
<td valign="top"><pre>
src/schema/v2/homeView
├── HomeViewComponent.ts
├── HomeViewSection.ts
├── __tests__
│   ├── HomeView.test.ts
│   └── HomeViewSection.test.ts
├── activityResolvers.ts
├── articlesResolvers.ts
├── artistResolvers.ts
├── artworkResolvers.ts
├── auctionResultsResolvers.ts
├── featuredFairsResolver.ts
├── getSectionsForUser.ts
├── heroUnitsResolver.ts
├── index.ts
├── marketingCollectionsResolver.ts
├── salesResolver.ts
├── sections.ts
├── withHomeViewTimeout.ts
└── zones
    ├── __tests__
    └── legacy.ts
</pre></td>

<td valign="top"><pre>
src/schema/v2/homeView
├── HomeViewComponent.ts
├── HomeViewSection.ts
├── __tests__
│   ├── HomeView.test.ts
│   └── HomeViewSection.test.ts
├── helpers
│   ├── getSectionsForUser.ts
│   └── withHomeViewTimeout.ts
├── index.ts
├── resolvers
│   ├── activityResolvers.ts
│   ├── articlesResolvers.ts
│   ├── artistResolvers.ts
│   ├── artworkResolvers.ts
│   ├── auctionResultsResolvers.ts
│   ├── featuredFairsResolver.ts
│   ├── heroUnitsResolvers.ts
│   ├── marketingCollectionsResolvers.ts
│   └── salesResolvers.ts
├── sections
│   └── index.ts
└── zones
    ├── __tests__
    └── legacy.ts
</pre></td>
</tr>
<tr>
<td valign="top"></td>
<td valign="top"></td>
</tr>
</table>

### CODE REVIEW

**Review by olerichter00 — APPROVED** [review]
Thanks a lot for organizing the files! 🧹🧹🧹 🤩

**Review by nickskalkin — APPROVED** [review]
👍

**Review by dblandin — APPROVED** [review]
Looks good! I'm also in favor of co-locating the resolver logic as you suggest in https://github.com/artsy/metaphysics/pull/6010 👍🏼

**Review by MounirDhahri — APPROVED** [review]
clean 👏 👏 👏

**Pull request merged**
